### ISSUE TITLE
Question about negative samples

### ISSUE THREAD

**Issue by Na-Z** [peisuke/MomentumContrast.pytorch#6]
Hi, thanks for your code.

I have a question about the negative samples in the queue. Is a sample with the same class as the query sample also considered as negative?

**Comment by RyanLiut** [comment]
I think yes because it follows "a simple instance discrimination task" as the paper said.

**Comment by Na-Z** [comment]
> I think yes because it follows "a simple instance discrimination task" as the paper said.

I see. Thanks.
